[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pokemonred"
version = "0.1.0"
description = "Pokemon Red RL experiments"
authors = [{name="Unknown"}]
requires-python = ">=3.8"
dependencies = [
    "pyboy",
    "gymnasium",
    "numpy",
]
